### ISSUE TITLE
1.18.2 此mod加载失败

### ISSUE THREAD

**Issue by FengLiuli** [Satxm/mcwifipnp#23]
[错误报告-2023-06-16_09.11.52.zip](https://github.com/Satxm/mcwifipnp/files/11764768/-2023-06-16_09.11.52.zip)
![KBQ{ {K8Q2OCME395S36E(H](https://github.com/Satxm/mcwifipnp/assets/51710792/fb3ff44a-8baf-417d-9232-c41f9b84e8ca)

**Comment by Satxm** [comment]
截图没有我的mod

**Comment by SheepYhangCN** [comment]
![{33EFDBF2-C199-487a-8FEB-75CC0D2D7642}](https://github.com/Satxm/mcwifipnp/assets/44539204/5b3981c6-b86b-4ed5-b0d9-e061b9c8a2cb)
我也遇到了这个问题 使用1.18.2 Forge 40.2.14 wifipnp 1.6.2
虽然fml报错没有显示wifipnp 但是在fml的crash report中每个mod的报错中都包含一行
`Caused by 2: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mcwifipnp.mixins.json:PlayerListAccessor] from phase [DEFAULT] in config [mcwifipnp.mixins.json] FAILED during APPLY`
且删除wifipnp后就恢复正常
之前没有这问题 可能是Forge更新造成的？

完整crash-report：
[crash-2023-11-10_23.02.07-fml.txt](https://github.com/Satxm/mcwifipnp/files/13320692/crash-2023-11-10_23.02.07-fml.txt)
完整log：
[latest.log](https://github.com/Satxm/mcwifipnp/files/13320699/latest.log)
@Satxm
